DROP SCHEMA IF EXISTS "rogin" CASCADE;

DROP USER IF EXISTS vasilii;

DROP DATABASE IF EXISTS "rogin";

CREATE USER vasilii WITH PASSWORD '123123';

CREATE DATABASE "rogin";

GRANT ALL privileges ON DATABASE rogin TO vasilii;

